---
title: "Supplemental Material Figures S5 and S6, Smith and Edwards 2020, Improved  status and trend estimates from the North American Breeding Bird Survey using a Bayesian hierarchical generalized additive model"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(ggplot2)
library(captioner)

```

<!-- load figures and species -->
```{r, echo = FALSE}

load("c:/GAM_Paper_Script/figures/supplement/all_suppl_figures.RData")
overall_comparison = overall.comparison
species <- names(svplots1)

capt_s1 = captioner(prefix = "S",levels = 2,
          auto_space = F,type = c("n","C"),infix = ".")
for(i in 1:4){
capt_s1(name = paste0(paste(i)),caption = paste0("Predicted survey-wide population trajectories from four models applied to the ", i, " data from the BBS. The stacked dots along the x axis indicate the approximate number of BBS counts used in the model; each dot represents 50 counts."),
          level = 1)
  
}

```



```{r, echo = FALSE}

bump(capt_s1,level = 1)
capts <- vector(length = length(species))
names(capts) <- species
for (sp in species)
{
  capts[sp] <- capt_s1(name = paste0(sp,"five"),caption = paste0("Predicted survey-wide population trajectories from four models applied to the ", sp, " data from the BBS. The stacked dots along the x axis indicate the approximate number of BBS counts used in the model; each dot represents 50 counts."),
          level = 2)

}

```

```{r svplots5, fig.cap = capts,echo=FALSE}


for(sp in species){
   print(svplots5[[sp]])
  cat("\n\n")

}

```





```{r, echo = FALSE}

bump(capt_s1,level = 1)

capts <- vector(length = length(species))
names(capts) <- species
for (sp in species)
{
  capts[sp] <- capt_s1(name = paste0(sp,"six"),caption = paste0("Annual differences in predictive fit between the GAMYE and SLOPE (blue) and the GAMYE and DIFFERENCE model (red) for ", sp),
          level = 2)

}

```

```{r svplots6, fig.cap = capts,echo=FALSE}


for(sp in species){
   print(svplots6[[sp]])
  cat("\n\n")

}

```


